name: Build

on:
  push:
    branches: [main]
    paths: 
      - 'src/**' # ** means wildcard to match child folders or files
  pull_request:
    branches: '*' #all branches
    paths: 
      - 'src/**' # ** means wildcard to match child folders or files
  #pull_request:
  #branches: [develop] # develop or main etc

permissions: read-all

jobs:
  build: # This is job name
    name: Build application
    runs-on: ubuntu-latest #or macos-latest

    steps:
      - run: node --version
      - run: npm --version
