name: CI

on:
  push:
    branches:
      - main
    paths:
      - src/**

  pull_request:
    branches:
      - main
    paths:
      - src/**

  workflow_dispatch: {}

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Something
        run: echo "Build job. . ."

  test:
    name: Test project
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Unit tests
        run: echo "Unit tests command. . ."
      - name: Integration tests
        run: echo "Integration tests command. . ."

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Display a message
        run: echo "Create release job. . ."

  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production
        run: echo "Deploying project . . ."
