name: Example9

on:
  # This workflow will run after Example8 completed
  # https://chat.openai.com/c/9f40bf08-22e3-4822-8f05-fe4350946c2f
  workflow_run:
    workflows: ['Example8']
    types:
      - completed

jobs:
  build:
    name: some title here #TODO: Change title
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: My-Artifact-Name #TODO: Artifact name here
          #path: build/artifact.apk #TODO: Path of the artifact

      - name: Display the structure of downloaded artifacts/files
        run: ls -R
